version: "3.7"
services:
  db:
      image: "postgres:latest"
      environment:
        PGDATA: /tmp
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: desafio-finderup-db
      volumes:
        - ./pgdata:/var/lib/postgresql/data
      network_mode: host
      ports:
        - "5432:5432"
  app:
      container_name: desafio-finderup-api
      restart: always
      build: .
      network_mode: host
      depends_on:
        - db